export const CATEGORIES = [
  'Produce',
  'Dairy',
  'Meat & Seafood',
  'Pantry',
  'Frozen',
  'Bakery',
  'Other',
] as const;

export type Category = (typeof CATEGORIES)[number];

// Comprehensive keyword mapping for each category
const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  Produce: [
    'apple',
    'apples',
    'banana',
    'bananas',
    'orange',
    'oranges',
    'grape',
    'grapes',
    'berry',
    'berries',
    'strawberry',
    'blueberry',
    'blackberry',
    'raspberry',
    'lettuce',
    'spinach',
    'kale',
    'arugula',
    'cabbage',
    'broccoli',
    'cauliflower',
    'carrot',
    'carrots',
    'celery',
    'onion',
    'onions',
    'garlic',
    'potato',
    'potatoes',
    'tomato',
    'tomatoes',
    'cucumber',
    'zucchini',
    'bell pepper',
    'pepper',
    'peppers',
    'mushroom',
    'mushrooms',
    'avocado',
    'avocados',
    'lemon',
    'lemons',
    'lime',
    'limes',
    'fresh herbs',
    'basil',
    'cilantro',
    'parsley',
    'rosemary',
    'thyme',
    'oregano',
  ],
  Dairy: [
    'milk',
    'cream',
    'half and half',
    'heavy cream',
    'butter',
    'buttermilk',
    'cheese',
    'cheddar',
    'mozzarella',
    'parmesan',
    'swiss',
    'feta',
    'goat cheese',
    'cottage cheese',
    'cream cheese',
    'sour cream',
    'yogurt',
    'greek yogurt',
    'eggs',
    'egg',
    'margarine',
  ],
  'Meat & Seafood': [
    'beef',
    'steak',
    'ground beef',
    'beef chuck',
    'beef brisket',
    'roast beef',
    'pork',
    'pork chop',
    'pork chops',
    'bacon',
    'ham',
    'sausage',
    'sausages',
    'chicken',
    'chicken breast',
    'chicken thigh',
    'chicken wings',
    'ground chicken',
    'turkey',
    'ground turkey',
    'turkey breast',
    'salmon',
    'tuna',
    'cod',
    'tilapia',
    'shrimp',
    'crab',
    'lobster',
    'scallops',
    'fish',
    'seafood',
    'anchovy',
    'anchovies',
    'sardine',
    'sardines',
  ],
  Pantry: [
    'flour',
    'sugar',
    'brown sugar',
    'salt',
    'pepper',
    'black pepper',
    'black peppercorns',
    'olive oil',
    'vegetable oil',
    'canola oil',
    'coconut oil',
    'sesame oil',
    'vinegar',
    'balsamic vinegar',
    'white vinegar',
    'apple cider vinegar',
    'soy sauce',
    'worcestershire',
    'hot sauce',
    'ketchup',
    'mustard',
    'mayonnaise',
    'canned',
    'tomato',
    'tomatoes',
    'beans',
    'black beans',
    'kidney beans',
    'rice',
    'pasta',
    'noodles',
    'bread',
    'breadcrumbs',
    'panko',
    'broth',
    'stock',
    'chicken broth',
    'beef broth',
    'vegetable broth',
    'spices',
    'paprika',
    'cumin',
    'coriander',
    'turmeric',
    'curry',
    'cinnamon',
    'nutmeg',
    'ginger',
    'vanilla',
    'vanilla extract',
    'almond extract',
    'honey',
    'maple syrup',
    'molasses',
  ],
  Frozen: [
    'frozen',
    'frozen peas',
    'frozen corn',
    'frozen vegetables',
    'ice cream',
    'sorbet',
    'gelato',
    'popsicle',
    'popsicles',
    'frozen chicken',
    'frozen fish',
    'frozen shrimp',
    'frozen fruit',
    'frozen berries',
    'frozen mango',
  ],
  Bakery: [
    'bread',
    'loaf',
    'baguette',
    'sourdough',
    'whole wheat',
    'multigrain',
    'croissant',
    'croissants',
    'roll',
    'rolls',
    'bun',
    'buns',
    'hamburger bun',
    'cake',
    'muffin',
    'muffins',
    'cookie',
    'cookies',
    'donut',
    'donuts',
  ],
  Other: [], // Fallback category
};

// Categorize an ingredient based on its name
export const categorizeIngredient = (ingredientName: string): Category => {
  const lowerName = ingredientName.toLowerCase().trim();

  // Check each category's keywords
  for (const category of CATEGORIES) {
    if (category === 'Other') {
      continue;
    }

    const keywords = CATEGORY_KEYWORDS[category];
    for (const keyword of keywords) {
      if (lowerName.includes(keyword)) {
        return category;
      }
    }
  }

  return 'Other';
};
